### ISSUE TITLE
Add instructions on how to deal with older files that are to be replaced but contain useful info

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.utils#100]
- Add instructions on how to deal with older files that are to be replaced but contain useful information such as LICENSE files.

**Comment by sbillinge** [comment]
@bobleesj I think this issue should be on the cookiecutter....amiright?

**Comment by bobleesj** [comment]
> @bobleesj I think this issue should be on the cookiecutter....amiright?

Right, this issue is now addressed in the instruction.
