### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by Filippo1598** [diffpy/diffpy.utils#126]
Referring to this in README:

`The diffpy.utils package provides functions for extracting array data from variously formatted text files, an interpolation function based on the Whittaker-Shannon formula that can be used to resample a PDF or other profile function over a new grid, Diffraction_objects for conveniently manipulating diffraction data, and some wx GUI utilities used by the PDFgui program.`

Maybe could be added some examples or some explanation on how to manipulate data.

**Comment by sbillinge** [comment]
Examples are not needed in the README, but we may want to add a link to the documentation at this point in the documentation so it is easier for curious people to find out more.  Thanks @Filippo1598 for the suggestion

**Comment by alisnwu** [comment]
The recut added link to documentation, should I close this issue?

**Comment by sbillinge** [comment]
@alisnwu I did see that, so we can close this as done.  closing.....
