### ISSUE TITLE
Remove 1 warning - DeprecationWarning: pkg_resources is deprecated as an API 

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.utils#132]
Please see https://github.com/diffpy/diffpy.pdfmorph/issues/143

**Comment by bobleesj** [comment]
@alisnwu To be added to Phase 2(3.13 python release) milestone

**Comment by alisnwu** [comment]
@bobleesj unsure if pkg_resources is still in current diffpy.utils, changelog.rst documented "Remove use of pkg_resources (deprecated)" in v3.2.3

**Comment by bobleesj** [comment]
@alisnwu you are correct - seeing the error message again: `diffpy.utils-3.0.0-py3.7.egg` an older version is being installed. I believe this will be fixed once we release 3.5.0. let's close this issue after py313 support.

**Comment by sbillinge** [comment]
please close this after sufficient testing that it really is resolved in pdfmorph.

**Comment by bobleesj** [comment]
Closing - closed by https://github.com/diffpy/diffpy.pdfmorph/issues/144#issuecomment-2465993329
