### ISSUE TITLE
documentation for importing wsinterp from parsers error

### ISSUE THREAD

**Issue by alisnwu** [diffpy/diffpy.utils#137]
### Problem
<img width="514" alt="Screenshot 2024-10-26 at 4 21 17 PM" src="https://github.com/user-attachments/assets/842327f3-53ec-4e7a-8f4c-4147a03e0f3d">

The documentation says to import `wsinterp` from `diffpy.utils.parser` instead of `diffpy.utils.parser.resample` which at first made me think there was a bug for importing `wsinterp`

**Comment by alisnwu** [comment]
@bobleesj could you confirm this is a valid issue and maybe not because my environment is not set correctly

**Comment by sbillinge** [comment]
Thanks for catching that.  But, I wonder why `wsinterp` is in `parser` sub-package.  It is a utility function, not a parser.  We may want to modify that  of `diffpy.utils`.  What do you think?

**Comment by sbillinge** [comment]
please see #138 before fixing this.  This should be fixed after #138 is resolved.

**Comment by bobleesj** [comment]
@alisnwu I think we can now address this now.

**Comment by sbillinge** [comment]
closing as fixed by #169
