### ISSUE TITLE
move resamplers out of parsers?

### ISSUE THREAD

**Issue by sbillinge** [diffpy/diffpy.utils#138]
### Problem

Why are resamplers in the parsers sub-module, they are not parsers?

### Proposed solution

create a tools sub-package, or simply put the resamplers into tools.py?  Let's discuss what makes the most sense.  @Sparks29032 ?

**Comment by alisnwu** [comment]
@sbillinge @Sparks29032 
tools.py seems to only deal with user and package related functions. The documentation also has resampler in its own section, so should we just create a resampler sub-package? It would be `from diffpy.utils.resampler import wsinterp`

Or instead we could do `from diffpy.utils.tools.interpolation import wsinterp`

**Comment by Sparks29032** [comment]
I made a note in #145. I agree the import `from diffpy.utils.resample import wsinterp` (path `diffpy.utils.resample.wsinterp`) would be best.

**Comment by bobleesj** [comment]
@Sparks29032  `from diffpy.utils.resample import wsinterp` yeah, sounds good! @alisnwu let's proceed with this: `utils/resample.py`.
