### ISSUE TITLE
deprecate legacy resampler?

### ISSUE THREAD

**Issue by sbillinge** [diffpy/diffpy.utils#139]
### Problem

there is a legacy resampler in parsers.  @Sparks29032 was this from before or did you write this then write a better version.   In general, keeping around things that are not used is just technical debt and we should get rid of it. 

### Proposed solution

 If it is something from Pavol days we may want to keep it as other code is likely using it.  If we think the code that is using it should start using the wsinterp instead we should deprectate it which means that when it is called we print a warning message that it is deprecated and will be removed in a version two mid-bumps later but should be replaced with wsinterp, then make issues linked to two bumps later to remove it.

**Comment by sbillinge** [comment]
btw, in the past we tended to just remove things, we didn't deprecate properly.  There may be nice tools for doing this nicely.  We could check.

**Comment by Sparks29032** [comment]
Sorry I didn't get pinged for this. Yes, this was from Pavol's time.
