### ISSUE TITLE
better wording on the capture user names functionality

### ISSUE THREAD

**Issue by sbillinge** [diffpy/diffpy.utils#140]
### Problem

user-name metadata capture utility is not performing as hoped.

### Proposed solution

We want to be able to make it easy to capture user metadata which is why we have the workflow for capturing the user metadata but the user messages are resulting in behavior where we either don't capture the name or capture dummy information that then gets stored in a user variable for all time.  We need to nudge users to capture accurate data so that they can get credit for their work in the future.

**Comment by bobleesj** [comment]
@alisnwu

Providing a bit more context: https://github.com/diffpy/diffpy.labpdfproc/issues/118#issuecomment-2439743613 and the code is used here: https://github.com/diffpy/diffpy.labpdfproc/blob/666a5ebd96d42f0cf8837f797db5fdeb47e2d391/src/diffpy/labpdfproc/tools.py#L5

**Comment by bobleesj** [comment]
closed by the PR above

**Comment by bobleesj** [comment]
@sbillinge could you plz close this?
