### ISSUE TITLE
diffraction objects dump function: add functionality to support xtype=d

### ISSUE THREAD

**Issue by yucongalicechen** [diffpy/diffpy.utils#147]
### Problem

dump function only supports xtype=tth and q

### Proposed solution

add xtype=d as a third option, i.e.,
`elif xtype == "d":`
`      data_to_save = np.column_stack((self.on_d[0], self.on_d[1]))`

**Comment by bobleesj** [comment]
@yucongalicechen Thank you for raising this issue. As diffpy.utils is now maintained by newer members (myself included) who may not be familiar with all the package details as of now, could you please provide more context about this issue?

**Comment by yucongalicechen** [comment]
> @yucongalicechen Thank you for raising this issue. As diffpy.utils is now maintained by newer members (myself included) who may not be familiar with all the package details as of now, could you please provide more context about this issue?

yep sorry, thanks for commenting, I'll add more details to this!
