### ISSUE TITLE
fix typo for insert_scattering_quantity in diffraction_objects.py

### ISSUE THREAD

**Issue by yucongalicechen** [diffpy/diffpy.utils#173]
### Problem
In this function we have 
elif xtype.lower() in DQUANTITIES:
      self.on_tth = [np.array(xarray), np.array(yarray)]

### Proposed solution
Change self.on_tth to self.on_d.
Refer to #154 for previous progress.

**Comment by sbillinge** [comment]
I think this is fixed by #193, but please confirm and we can close

**Comment by yucongalicechen** [comment]
confirmed that this issue can be closed by #193
