### ISSUE TITLE
differaction objects improve functions q_to_tth, tth_to_q

### ISSUE THREAD

**Issue by yucongalicechen** [diffpy/diffpy.utils#174]
### Problem
Functions do not handle invalid cases (when tth > 180 or arcsin value > 1).

### Proposed solution
Raise valueerror for those cases. Refer to #154 for more details.

**Comment by sbillinge** [comment]
I am guessing this won't be a ValueError.  We can have it crash the way it does now (invalid arcsin) but we want to overload the error message to help the user know how to fix it.
