### ISSUE TITLE
write tests for...

### ISSUE THREAD

**Issue by sbillinge** [diffpy/diffpy.utils#187]
### Problem
- [ ] __eq__
- [ ] __add__
- [ ] __radd__
- [ ] __sub__
- [ ] __rsub__
- [ ] __mul__
- [ ] __rmul__
- [ ] __truediv__
- [ ] __rtruediv__

before doing this talk to @yucongalicechen or @sbillinge about new data structure for the arrays in the DOs.

**Comment by bobleesj** [comment]
For future test writers, please read the discussions via in-line comments: https://github.com/diffpy/diffpy.utils/pull/225.

**Comment by bobleesj** [comment]
@sbillinge I am trying to write tests for these. Two important questions below:

Q1. What's the difference between, for example `mul` and `rmul` shown below?

```python
    def __mul__(self, other):
        multiplied = deepcopy(self)
        if isinstance(other, int) or isinstance(other, float) or isinstance(other, np.ndarray):
            multiplied.on_tth[1] = other * self.on_tth[1]
            multiplied.on_q[1] = other * self.on_q[1]
        elif not isinstance(other, DiffractionObject):
            raise TypeError("I only know how to multiply two Scattering_object objects")
        elif self.on_tth[0].all() != other.on_tth[0].all():
            raise RuntimeError(x_grid_emsg)
        else:
            multiplied.on_tth[1] = self.on_tth[1] * other.on_tth[1]
            multiplied.on_q[1] = self.on_q[1] * other.on_q[1]
        return multiplied

    def __rmul__(self, other):
        multiplied = deepcopy(self)
        if isinstance(other, int) or isinstance(other, float) or isinstance(other, np.ndarray):
            multiplied.on_tth[1] = other * self.on_tth[1]
            multiplied.on_q[1] = other * self.on_q[1]
        elif self.on_tth[0].all() != other.on_tth[0].all():
            raise RuntimeError(x_grid_emsg)
        else:
            multiplied.on_tth[1] = self.on_tth[1] * other.on_tth[1]
            multiplied.on_q[1] = self.on_q[1] * other.on_q[1]
        return multiplied
```

Q2. We've made `all_arrays` immutable - This makes the existing  `__mul__`, `__add__` methods invalid. We must create a new object. For example, the `on_tth` function above within `__mul__`  isn't valid  since it can't modify `all_arrays`.

I am thinking we might have to change from

```python
    def __add__(self, other):
        summed = deepcopy(self)
        if isinstance(other, int) or isinstance(other, float) or isinstance(other, np.ndarray):
            summed.on_tth[1] = self.on_tth[1] + other
            summed.on_q[1] = self.on_q[1] + other
        elif not isinstance(other, DiffractionObject):
            raise TypeError("I only know how to sum two DiffractionObject objects")
        elif self.on_tth[0].all() != other.on_tth[0].all():
            raise RuntimeError(x_grid_emsg)
        else:
            summed.on_tth[1] = self.on_tth[1] + other.on_tth[1]
            summed.on_q[1] = self.on_q[1] + other.on_q[1]
        return summed
```

to

```python
    def __add__(self, other):
        if not isinstance(other, DiffractionObject):
            raise TypeError("I only know how to sum two DiffractionObject objects")
        tth_sum = self.on_tth[1] + other.on_tth[1]
        return DiffractionObject(xarray=tth_sum, yarray=self.yarray, xtype="tth", wavelength=self.wavelength)
```

The above assumes 1) self's yarray is used in the new object 2) tth xtype is used 3) and the self's wavelength is used.

**Comment by sbillinge** [comment]
> Q1. What's the difference between, for example `mul` and `rmul` shown below?

they are the same because the mul operation commutes.

**Comment by sbillinge** [comment]
> Q2. We've made `all_arrays` immutable - This makes the existing `__mul__`, `__add__` methods invalid. We must create a new object. For example, the `on_tth` function above within `__mul__` isn't valid since it can't modify `all_arrays`.

Those arrays are not immutable, we just made them not settable, right?  I think we can update them how we want inside a method.

**Comment by bobleesj** [comment]
> Those arrays are not immutable, we just made them not settable,

Right, `all_arrays` isn't settable. I guess we can modify `_all_arrays` internally which is mutable.

**Comment by bobleesj** [comment]
Since 3.6.0 deadline is approaching, I will resolve this issue

**Comment by bobleesj** [comment]
I will keep progress here:

- [ ] eq
- [ ] add
- [ ] radd
- [ ] sub
- [ ] rsub
- [ ] mul
- [ ] rmul - same as mul, not needed
- [ ] truediv
- [ ] rtruediv
