### ISSUE TITLE
write new tests for (init functionality)

### ISSUE THREAD

**Issue by sbillinge** [diffpy/diffpy.utils#188]
### Problem
- [ ] __init__  I think this is mostly done by #193 but please check news, docs and tests
- [ ] insert_scattering_object (move to __init__) .  I think this is mostly done by #193 but please check news, docs and tests
- [ ] set_angles_from_list (make private, move to __init__)
- [ ] set_angles_from range (make private, move to __init__)
- [ ] set_qs_from range (make private, move to __init__)

**Comment by yucongalicechen** [comment]
> @sbillinge just for clarification
> 
> In order to to use one of the methods (`_set_angles_from_list`) within `init`, would you like to have an extra parameter from
> 
> ```python
> class DiffractionObject:
>     def __init__(
>         self, name=None, ..., xarray=None, yarray=None, xtype=None
>     ):
> ```
> 
> to
> 
> ```python
> class DiffractionObject:
>     def __init__(
>         self, name=None, ..., xarray=None, yarray=None, angles_list=None
>     ):
> 
>     ....
> 
>     if angles_list:
>         self._set_angles_from_list(angles_list)
> ```
> 
> in order to optionally use the `_set_angles_from_list` method?
> 
> ```python
>     def _set_angles_from_list(self, angles_list):
>         self.angles = angles_list
>         self.n_steps = len(angles_list) - 1.0
>         self.begin_angle = self.angles[0]
>         self.end_angle = self.angles[-1]
> ```

I think the angles here is on_tth(). See discussions in #191

**Comment by sbillinge** [comment]
yes, @bobleesj , the UC is 

1. crystallographer wants to generate an x-array on a grid
2. crystallogrpher (cr) inputs, start, stop, step, xtype
3. DO creates xtype-array on this grid, and populates the other x-grids automatically.

I am not sure how this will be used tbh because there needs to be a yarray and this needs a matching xarray, so maybe we don't need this.    But if there is already a yarray and the person wants everything on a different grid, a UC would be

1. cr instantiates a DO with and xarray and a yarray and an xtype
2.  cr wants it on a different xarray
3. cr supplies start, stop, step xtype 
4. DO generates new xarrays on this grid
5. DO interpolates the yarray onto this grid and replaces the old yarray with this one

Again, I wonder actually how useful this would be.   Maybe it is better to put it into an issue and leave it in case someone asks for it.  The same would go for other ways to generate arrays.

**Comment by bobleesj** [comment]
@sbillinge Re-visiting this again,

is it a common practice for cr to modify/interpolate xarrays/yarrays?

If so, maybe the `init` wouldn't the best place but rather a separate public method that resets `xarrays/yarrays` and  `_all_arrays` internally?

I could work on other issues if we decide not to have this for 3.6.0 release.

**Comment by bobleesj** [comment]
@sbillinge I've created an issue above. 

Could we close this issue since you've provided init tests?

**Comment by yucongalicechen** [comment]
@bobleesj Something new to add in insert_scattering_quantity: (1) check xarray empty or not, if not check that yarray is the same length as xarray and xtype is valid (one of XQUANTITIES), (2) set attribute so that we don't allow setting an invalid xtype.

**Comment by bobleesj** [comment]
> @bobleesj Something new to add in insert_scattering_quantity: (1) check xarray empty or not, if not check that yarray is the same length as xarray and xtype is valid (one of XQUANTITIES), (2) set attribute so that we don't allow setting an invalid xtype.

When you say add sth new, are we referring to adding new tests or a new feature within the method? If it is a new feature within the method, i think its better to have a separate issue for this?

**Comment by yucongalicechen** [comment]
> > @bobleesj Something new to add in insert_scattering_quantity: (1) check xarray empty or not, if not check that yarray is the same length as xarray and xtype is valid (one of XQUANTITIES), (2) set attribute so that we don't allow setting an invalid xtype.
> 
> When you say add sth new, are we referring to adding new tests or a new feature within the method? If it is a new feature within the method, i think its better to have a separate issue for this?

add new features, sorry, and yes I will make a new issue for this

**Comment by sbillinge** [comment]
closed as completed in #193
