### ISSUE TITLE
Utilize `set_angles_from_list`, `set_angles_from`, `set_qs_from_range` methods later if requested

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.utils#198]
### Problem

Our `DiffractionObject` contains the following methods that are not currently being used:

`set_angles_from_list`, `set_angles_from`, `set_qs_from_range`:

```python
    def _set_angles_from_list(self, angles_list):
        self.angles = angles_list
        self.n_steps = len(angles_list) - 1.0
        self.begin_angle = self.angles[0]
        self.end_angle = self.angles[-1]

    def _set_qs_from_range(self, begin_q, end_q, step_size=None, n_steps=None):
        """
        create an array of linear spaced Q-values

        Parameters
        ----------
        begin_q float
          the beginning angle
        end_q float
          the ending angle
        step_size float
          the size of the step between points.  Only specify step_size or n_steps, not both
        n_steps integer
          the number of steps.  Odd numbers are preferred. Only specify step_size or n_steps, not both

        Returns
        -------
        Sets self.qs
        self.qs array of floats
          the q values in the independent array

        """
        self.qs = self._set_array_from_range(begin_q, end_q, step_size=step_size, n_steps=n_steps)

    def _set_angles_from_range(self, begin_angle, end_angle, step_size=None, n_steps=None):
        """
        create an array of linear spaced angle-values

        Parameters
        ----------
        begin_angle float
          the beginning angle
        end_angle float
          the ending angle
        step_size float
          the size of the step between points.  Only specify step_size or n_steps, not both
        n_steps integer
          the number of steps.  Odd numbers are preferred. Only specify step_size or n_steps, not both

        Returns
        -------
        Sets self.angles
        self.angles array of floats
          the q values in the independent array

        """
        self.angles = self._set_array_from_range(begin_angle, end_angle, step_size=step_size, n_steps=n_steps)
```

The above methods could be used for the following UCs in mind written by @sbillinge below:

--- 
1. crystallographer wants to generate an x-array on a grid
2. crystallogrpher (cr) inputs, start, stop, step, xtype
3. DO creates xtype-array on this grid, and populates the other x-grids automatically.

I am not sure how this will be used tbh because there needs to be a yarray and this needs a matching xarray, so maybe we don't need this.    But if there is already a yarray and the person wants everything on a different grid, a UC would be

1. cr instantiates a DO with and xarray and a yarray and an xtype
2.  cr wants it on a different xarray
3. cr supplies start, stop, step xtype 
4. DO generates new xarrays on this grid
5. DO interpolates the yarray onto this grid and replaces the old yarray with this one

Again, I wonder actually how useful this would be.   Maybe it is better to put it into an issue and leave it in case someone asks for it.  The same would go for other ways to generate arrays.

_Originally posted by @sbillinge in https://github.com/diffpy/diffpy.utils/issues/188#issuecomment-2518664976_
            
---

### Proposed solution

As written above, it would be better  to make an issue here and address the above needs once User asks for this specific feature.

**Comment by bobleesj** [comment]
Update update:

> ... I think we are going to kill for making arrays from ranges. I couldn't come up with a good usecase for them because I think the stay had to be set by the y-array so I couldn't think of a time I would actually use that

by @sbillinge  - https://github.com/diffpy/diffpy.utils/issues/53#issuecomment-2540008827

**Comment by sbillinge** [comment]
I'm closing this.  I think it is just distracting keeping it around.  Sometimes we want to keep around good ideas for later, but this seems like an idea that (a) isn't good (it was my idea!) (b) if it is useful, it will occur to us later because we need it.  Therefore I am closing this.

**Comment by bobleesj** [comment]
@sbillinge Can I remove these util functions from the package? Since @yucongalicechen has started writing docs and docstrings, thought it would be best to keep it as portable as possible. But, I have written those test functions explicitly above.

**Comment by sbillinge** [comment]
yes, remove all trace of these and any tests.
