### ISSUE TITLE
insert_scattering_quantity check valid arrays and xtypes

### ISSUE THREAD

**Issue by yucongalicechen** [diffpy/diffpy.utils#200]
### Proposed solution

In the `insert_scattering_quantity` function, we want to add these features: (1) check if xarray is empty or not, if not check that yarray has the same length as xarray and xtype is valid (one of XQUANTITIES), (2) set attribute so that we don't allow setting an invalid xtype.

**Comment by bobleesj** [comment]
@yucongalicechen 

For (2) could you clarify what "attribute" here means?

**Comment by yucongalicechen** [comment]
> @yucongalicechen
> 
> For (2) could you clarify what "attribute" here means?

Yeah, it's the similar idea from #194. Use @property to raise a value error if `xtype` is not one of the `XQUANTITIES`.

**Comment by bobleesj** [comment]
Thanks! I understand it now - using a property decorator
