### ISSUE TITLE
update docs diffpy.utils.tools

### ISSUE THREAD

**Issue by sbillinge** [diffpy/diffpy.utils#210]
moved from #208 

btw @alisnwu I closed this before reading https://www.diffpy.org/diffpy.utils/examples/toolsexample.html but there I saw no clear information about how to update the default user information. I would put it as an enumerated list to make it clearer. there are at least 4 different ways of setting these things with more or less permanence. Make it as an enumerated list. But also discuss with and example how to updage your default file using a text editor.

Also, is this a typo?

from diffpy.utils.tools import get_user_info
package_metadata = get_package_info("my_package")

**Comment by bobleesj** [comment]
@alisnwu I heard from @yucongalicechen that finals are done today. 

Could you please resolve care of this issue and also a minor fix requested by @sbillinge in https://github.com/diffpy/diffpy.utils/pull/207?

**Comment by alisnwu** [comment]
Yep! Will work on everything this weekend

**Comment by bobleesj** [comment]
Great!
