### ISSUE TITLE
mu T calculator (UC1)

### ISSUE THREAD

**Issue by yucongalicechen** [diffpy/diffpy.utils#218]
### Problem

UC1:
1. user places sample on diffractometer
2. diffractometer determines weight and dimensions of the sample
3. diffractometer shares this information with diffpy.utils
4. diffpy.utils computes muD

(See more discussions in #45)

**Comment by sbillinge** [comment]
This is not a diffpy.utils UC.  Not sure where to put it but probably labpdfproc?

**Comment by yucongalicechen** [comment]
moved this to https://github.com/diffpy/diffpy.labpdfproc/issues/144
