### ISSUE TITLE
mu T calculator (UC4)

### ISSUE THREAD

**Issue by yucongalicechen** [diffpy/diffpy.utils#220]
### Problem

UC4
1. user selects "compute muD from known density" radio button
2. labpdfproc.mudCalc presents a form pre-filled with defaults containing fields for user to enter mass density in g/cm^3, composition (e.g. ZrO2), wavelength(angstroms), D (mm). Defaults are <Till's zirconia number>, , , 1.
3. user clicks run calc
4. lpp.mudCalc returns the calculated value as output without running the cve calc.

(originally from comment in #45)

**Comment by sbillinge** [comment]
This seems to be a labpdfproc issue, why is it here?

**Comment by sbillinge** [comment]
@yucongalicechen you can close issues here if and when we move them to labpdfproc

**Comment by yucongalicechen** [comment]
moved this issue to https://github.com/diffpy/diffpy.labpdfproc/issues/143
