### ISSUE TITLE
doc for transforms (q_to_tth, tth_to_q, etc.)

### ISSUE THREAD

**Issue by yucongalicechen** [diffpy/diffpy.utils#226]
### Problem

We kind of started this work in https://github.com/diffpy/diffpy.utils/pull/178, but the functions have changed quite a lot since then. I think it's a good time to wrap this up.

**Comment by yucongalicechen** [comment]
^not sure if we should put this in 3.6.0 release or 3.7.0 release

**Comment by bobleesj** [comment]
looks 3.6.0 to be .. :)
