### ISSUE TITLE
Use `lowercase_with_underscore.rst`  naming convention for doc files

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.utils#238]
Creating an issue for now:

---
@sbillinge Do we want to use `lower_with_underscore` for doc .rst files? A bit hard to read `diffractionobjectsexample.rst`. Not sure about the convention. Did a quick search and appears `NumPy` is using the `lower_with_underscore` convention (mostly, not all) https://github.com/numpy/numpy/tree/main/doc/source/reference

@bobleesj @yucongalicechen yes, let's use this convention.  But I don't worry too much for now, I will just merge this.

_Originally posted by @sbillinge in https://github.com/diffpy/diffpy.utils/issues/237#issuecomment-2544131453_

**Comment by yucongalicechen** [comment]
I can take this issue! It's just changing the file names, right? @bobleesj

**Comment by bobleesj** [comment]
Yup @yucongalicechen!
