### ISSUE TITLE
docs: Double-check and refine docstrings before `3.6.0` release

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.utils#239]
- Use consistent NumPy docstrings style
- Ensure API docs remain clear for new maintainers and users with limited programming experience.

---
              maybe we could further refine docstrings in separate issues? @sbillinge

_Originally posted by @bobleesj in https://github.com/diffpy/diffpy.utils/pull/228#discussion_r1885354175_

**Comment by sbillinge** [comment]
would this be a good kind of group hackathon? everyone take a few?  Also a learning/teaching experience?

**Comment by bobleesj** [comment]
Yeah, early next week would be best. I will shift my gears for crystallography for the next 3 days..

I can lead a quick rundown of our group's testing standards and assign members to improve docstrings collaboratively during a call.
