### ISSUE TITLE
I think the `get_user_info` docs don't match the code

### ISSUE THREAD

**Issue by sbillinge** [diffpy/diffpy.utils#245]
### Problem
The docs don't seem to correspond to the code.

I was tweaking the docs and checking the code.  Places where I didn't update the docs it is because I think the docs are better behavior than the code....

### Proposed solution
update the code to match the docs (with tests).

One thing I remember concretely is that `get_user_info` gets an optional argument of `args` that is type argparse.Namespace but the docs say a dict can be passed.

Since we decided to make this a user-facing functionality that can be used by others, I think it is more reusable if it takes a dict and not the full args Namespace?

But there may be other things, so have someone go through the docs and type all the commands illustrated in there and make sure the code actually does what it says.

**Comment by yucongalicechen** [comment]
I think the codes and tests are all written in dict. There's a mistake in the docstring and the fact that we are using "args" as the variable name of a dictionary is confusing. Shall we change args to inputs?

Here's a snapshot of how we are using the function in labpdfproc:
![image2](https://github.com/user-attachments/assets/9a8c7e6e-d715-4493-93fd-2f6fb846dda3)

**Comment by sbillinge** [comment]
yes, I saw that.  I wrote the docs how I wanted it (to make this more reusable).  i.e., pass a dict not an argparse. Namespace, but also, do it optionally.

**Comment by yucongalicechen** [comment]
> yes, I saw that. I wrote the docs how I wanted it (to make this more reusable). i.e., pass a dict not an argparse. Namespace, but also, do it optionally.
I mean it's already implemented as what the docs wants. It's just poorly named. We have `def get_user_info(args=None)` but the args here is actually a dictionary.

**Comment by sbillinge** [comment]
The code also has to be updated as 'args.username' won't work with a dict. Let's think a bit what behavior we want

**Comment by sbillinge** [comment]
Let's call it 'user_info' and make it a dict. 

If runtime user data is passed in as an arg we will have to compose the dict from the args before paying it in.
