### ISSUE TITLE
fix XQUANTITIES in docstring

### ISSUE THREAD

**Issue by yucongalicechen** [diffpy/diffpy.utils#247]
@bobleesj in the docstring the XQUANTITIES is not showing. Shall I open a new issue or just comment on #239?

![4](https://github.com/user-attachments/assets/1acb8800-2670-4626-af48-8f75e84d7109)
![5](https://github.com/user-attachments/assets/ffa25bc3-54b8-4576-bf73-c9867c96a084)

_Originally posted by @yucongalicechen in https://github.com/diffpy/diffpy.utils/issues/246#issuecomment-2550013250_

**Comment by bobleesj** [comment]
@yucongalicechen do you mind addressing this one? I am away from keyboard till Thursday evening

**Comment by yucongalicechen** [comment]
> @yucongalicechen do you mind addressing this one? I am away from keyboard till Thursday evening

No prob, I already self-assigned this haha

**Comment by bobleesj** [comment]
If it works sth like,

> Must be one of "x, y, z" defined in XQUANTITY. 

Where x y z ... are dynamically rendered.

Hitting 2 birds (user, dev facing) at once?

**Comment by sbillinge** [comment]
I would just leave it tbh.  In danger of just making it worse here
