### ISSUE TITLE
Do we want to call the DO unique id as `id` or `uuid`?

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.utils#269]
_Originally posted by @sbillinge in https://github.com/diffpy/diffpy.utils/pull/265#discussion_r1894953424_

I like `uuid` because it is not only specific but also it implies it's a variable/constant that the user should not play with.

**Comment by sbillinge** [comment]
I like the discussion. How about `_uuid`, which is even more hands off.

**Comment by bobleesj** [comment]
right, `_uuid` I like it - we (maintainers) will be the primary user of this variable. 

For regular users, they could use the "name" mutable variable, written in human language.

**Comment by bobleesj** [comment]
Will create a quick PR for this
