### ISSUE TITLE
Improve comments for @pytest.mark.parametrize test cases in `test_scale_to` function

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.utils#274]
@sbillinge ready for review.

@yucongalicechen , the part that is remaining is the `test_scale_to` function. 

The existing comments  like`# C2: Same length x-arrays with exact x-value match`, `# C3: Same length x-arrays with approximate x-value match` were abit hard for me to understand what's being tested. Would you mind improving this test comments for `test_scale_to` using the above format?

_Originally posted by @bobleesj in https://github.com/diffpy/diffpy.utils/issues/273#issuecomment-2560272419_

**Comment by yucongalicechen** [comment]
I can take this issue!
