### ISSUE TITLE
muD calculator for z-scan files

### ISSUE THREAD

**Issue by yucongalicechen** [diffpy/diffpy.utils#281]
move mud_calculator.py from labpdfproc to here

Check https://github.com/diffpy/diffpy.labpdfproc/blob/main/src/diffpy/labpdfproc/mud_calculator.py
and https://github.com/diffpy/diffpy.labpdfproc/blob/main/tests/test_mud_calculator.py.

**Comment by sbillinge** [comment]
btw @bobleesj we can put this switch into the 3.7.0 release if we want.  It shouldn't hold up 3.6.0

**Comment by bobleesj** [comment]
yeah @yucongalicechen 3.7.0 would be good..

**Comment by bobleesj** [comment]
@sbillinge
