### ISSUE TITLE
DiffractionObject.scale_to() default is to scale to maxima

### ISSUE THREAD

**Issue by sbillinge** [diffpy/diffpy.utils#287]
### Problem
Sorry guys, this is a scope creep, but I had an a idea to make the `scale_to()` method more useful so that it can be run with no xvalue passed and still work by default. 

### Proposed solution
 It would be something like this:
```
scaled_do = my_do.scaled_to(target_do)
```
and the default scaling would simply be `max(target_do.on_q()[0])/max(my_do.on_q()[0])`

if user passes in an xvalue, and xtype we go to the current workflow.  This allows the user to override the default behavior when it doesn't work for some reason, for example they want to scale to a diffraction feature but there is small angle scattering in the signal, or the maximum peak in one pattern is a different peak or something.

**Comment by yucongalicechen** [comment]
I can take this issue!

**Comment by sbillinge** [comment]
I just saw an error, it should be on_q()[1], the y-array.  Even better we can do it directly from the all_arrays[:,0]
