### ISSUE TITLE
fix: revisit tests for DO operations

### ISSUE THREAD

**Issue by yucongalicechen** [diffpy/diffpy.utils#298]
is the condition "same length xarray" or "on the same `q/tth/d-array`"?  I think it should be the latter or we are adding things incorrectly.  Please can you check the code.  If the code is doing it right, change the doc.  If hte doc is right, we probably should revisit hte tests and code.

_Originally posted by @sbillinge in https://github.com/diffpy/diffpy.utils/pull/297#discussion_r1899701202_

**Comment by bobleesj** [comment]
Could you check the _check_operation_function? Thats how the code checks for the shape modified by @sbillinge
