### ISSUE TITLE
docs: docstring for `on_d`, `on_q`, `on_tth`, and `dump` are missing

### ISSUE THREAD

**Issue by yucongalicechen** [diffpy/diffpy.utils#306]
@sbillinge Do we want to make `on_d`, `on_q`, `on_tth` private?

**Comment by sbillinge** [comment]
no.  Users can use these if they want

**Comment by yucongalicechen** [comment]
> no.  Users can use these if they want

Okay, then we should add docstring for these public functions..? I can make a PR for the docstring before this release

**Comment by sbillinge** [comment]
@yucongalicechen @bobleesj can confirm, but I think we are basically ready to build the docs and release, hopefully this evening, and I think this is the last non release-workflow PR.

**Comment by yucongalicechen** [comment]
> @yucongalicechen @bobleesj can confirm, but I think we are basically ready to build the docs and release, hopefully this evening, and I think this is the last non release-workflow PR.

Yep! I'm adding the docstrings right now. Will make a PR in a couple minutes. I also started working on the release checklist, that should be up soon.
