### ISSUE TITLE
Ready for 3.6.0rc PyPI/GitHub release

### ISSUE THREAD

**Issue by yucongalicechen** [diffpy/diffpy.utils#308]
### PyPI/GitHub rc-release preparation checklist:

- [x] All PRs/issues attached to the release are merged.
- [x] All the badges on the README are passing.
- [x] License information is verified as correct. If you are unsure, please comment below.
- [x] Locally rendered documentation contains all appropriate pages, including API references (check no modules are
      missing), tutorials, and other human-written text is up-to-date with any changes in the code.
- [x] Installation instructions in the README, documentation, and the website (e.g., diffpy.org) are updated.
- [x] Successfully run any tutorial examples or do functional testing with the latest Python version.
- [x] Grammar and writing quality are checked (no typos).
- [x] Install `pip install build twine`, run `python -m build` and `twine check dist/*` to ensure that the package can be built and is correctly formatted for PyPI release.

**Comment by yucongalicechen** [comment]
Confirmed API both local and online here: https://yucongalicechen.github.io/diffpy.utils/release.html.
Package can be built and is correctly formatted:
![image](https://github.com/user-attachments/assets/c8193ecc-eebc-4af5-9b3f-75dd2572a32c)

**Comment by sbillinge** [comment]
Thanks @yucongalicechen I will go ahead with the rc release!

**Comment by sbillinge** [comment]
@yucongalicechen @bobleesj the pre-release seemed to go without a hitch and showed green, thogh I am not seeing the `3.6.0rc0` pre-release on pypi for some reason.

**Comment by bobleesj** [comment]
@sbillinge  I am very glad that github admin authorization works..

ah, I am afraid `0.6.0` was entered?

<img width="593" alt="Screenshot 2024-12-31 at 5 47 01 PM" src="https://github.com/user-attachments/assets/86488ed8-5a71-4df3-bd38-096bd920ae4c" />

**Comment by bobleesj** [comment]
a quick question @sbillinge  did you split rc and full release issues on purpose? Indeed, it might be a good idea to split since it can be quite overwhelming

**Comment by sbillinge** [comment]
ah, that is the problem.  I will go again with 3.6

**Comment by sbillinge** [comment]
> a quick question @sbillinge did you split rc and full release issues on purpose? Indeed, it might be a good idea to split since it can be quite overwhelming

yes.  I created `3.6.0rc` `3.6.0 full` and `3.6.0 rollout` milestones and I wanted to close the issue so the milestone showed as completed.  If this is too much work moving forward we can do it differently.

**Comment by sbillinge** [comment]
closed as completed and released to pypi

**Comment by bobleesj** [comment]
@sbillinge good!

**Comment by sbillinge** [comment]
@yucongalicechen GitHub/PyPI pre-release done!

please make a PR into the conda-forge feedstock. Review and approve the PR. (I copied this from gitlab.... @bobleesj is this also the workflow for rc release to CF?

**Comment by bobleesj** [comment]
@sbillinge we didn't specify in the checklist to do `rc` release for conda-forge, but we do have an instruction on GitLab/cookiecutter doc. 

Should we modify the checklist so that we **always** do conda-forge pre-release?

**Comment by sbillinge** [comment]
I think maybe not.   That may be overkill

**Comment by bobleesj** [comment]
@sbillinge I agree because if PyPI is working, conda-forge should work... and we also have additional safe guard which is the conda-forge CI running pytest

**Comment by sbillinge** [comment]
@bobleesj I saw you ran a workflow to build the docs but how do I look at them?

**Comment by bobleesj** [comment]
https://github.com/diffpy/diffpy.utils/actions/workflows/publish-docs-on-release.yml

@sbillinge 

Shown above, I didn't run the workflow (no permission actually) but the title of the PR is `docs: deploy docs on github pre-release with tag push`... running `[Tests on PR](https://github.com/diffpy/diffpy.utils/actions/workflows/tests-on-pr.yml)

**Comment by sbillinge** [comment]
OK, I did a `3.6.0.rc1` pre-release to test this.

**Comment by bobleesj** [comment]
@sbillinge seems like your `main` wasn't synced before uploading the tag?

<img width="750" alt="Screenshot 2024-12-31 at 6 58 27 PM" src="https://github.com/user-attachments/assets/4deefb09-f312-4849-8535-5129bb82a0f2" />

The above title should be either written by since since you've merged my PR on adding `prerelease`

**Comment by sbillinge** [comment]
ugh, getting too tired here.  Sorry.  I pushed rc2
