### ISSUE TITLE
update diffpy.utils in diffpy-cmi environment?

### ISSUE THREAD

**Issue by till-schertenleib** [diffpy/diffpy.utils#40]
Installation worked fine, and the instructions were clear. - Great job!

However, I would suggest small changes in the email that will go out to the community. I think diffpy-cmi is the most popular tool that people are using. When I was reading, I wanted to install it in my python environment on my ubuntu subsystem, where I have installed diffpy-cmi. But I hesitated, because I didn't know if the new diffpy.utils will be compatible with all the other packages, or if some commands are working differently now which leads to problems when I want to run my jupyter notebooks etc.

So I just installed it as described on the GitHub page. 

If we already know that my concerns are mute, and everything is fully compatible and so on, we could write in the email that users are encouraged to update diffpy.utils in their diffpy-cmi environment since there are new features added to the library.

Best,

Till

**Comment by sbillinge** [comment]
Thanks Till, this is great!  Very helpful

**Comment by sbillinge** [comment]
closed as no longer needed.
