### ISSUE TITLE
Which release is the current one?

### ISSUE THREAD

**Issue by CJ-Wright** [diffpy/diffpy.utils#5]
I see a bunch of tags, many of them not sequential and the one that GitHub labels as the "latest" was published in Jan 2016, but there are also tags in May 2016?

**Comment by pavoljuhas** [comment]
diffpy.utils as other py3-fied packages has 2 branches: `master` for Python 2 maintenance and `python3`.  

Releases tagged as `v1.*` are on the `master` branch and are to stay compatible with diffpy-cmi 2.0 and PDFgui.

Releases tagged as `v3*` are on the `python3` branch and may introduce incompatible changes.

Short answer - the latest release for Python 2 is `v1.*` and for Python 3 it is `v3*`.

**Comment by pavoljuhas** [comment]
Can you post similar questions to [diffpy-dev](https://groups.google.com/forum/#!forum/diffpy-dev) in the future?
I think it could be of interest to other developers and interested users that are subscribed on diffpy-dev.
