### ISSUE TITLE
add tests for diffraction methods

### ISSUE THREAD

**Issue by sbillinge** [diffpy/diffpy.utils#53]

**Comment by sbillinge** [comment]
- [ ] __init__  (and insert_scattering_quantity)
- [ ] __eq__
- [ ] __add__
- [ ] __radd__
- [ ] __sub__
- [ ] __rsub__
- [ ] __mul__
- [ ] __rmul__
- [ ] __truediv__
- [ ] __rtruediv__
- [ ] set_angles_from_list (make private)
- [ ] set_angles_from range (make private, move to __init__)
- [ ] set_qs_from range (make private, move to __init__)
- [ ] get_angle_index
- [ ] set_all_arrays (make private)
- [ ] scale_to
- [ ] on x_type
- [ ] d_to_tth
- [ ] tth_to_d
- [ ] d_to_q
- [ ] q_to_d

**Comment by bobleesj** [comment]
@sbillinge could you remove 

```
eq
 add
 radd
 sub
 rsub
 mul
 rmul
 truediv
 rtruediv
```

from this issue?  These are provided in this issue: https://github.com/diffpy/diffpy.utils/issues/187 Also, if we could make small distinction based on the issue title, that would be great.

**Comment by sbillinge** [comment]
Done. I also removed the methods that I think we are going to kill for making arrays from ranges.  I couldn't come up with a good usecase for them because I think the stay had to be set by the y-array so I couldn't think of a time I would actually use that

**Comment by bobleesj** [comment]
@sbillinge  
Shall I make a PR that removes the methods for making arrays from ranges?

**Comment by bobleesj** [comment]
@sbillinge  We have `set_all_arrays (make private)` left in this issue:

Does the following close this issue? This following code is implemented in the `main` branch by PR https://github.com/diffpy/diffpy.utils/pull/196:

```python
def test_all_array_getter():
    actual_do = DiffractionObject(
        xarray=np.array([0.0, 90.0, 180.0]),
        yarray=np.array([1.0, 2.0, 3.0]),
        xtype="tth",
        wavelength=4.0 * np.pi,
    )
    expected_all_arrays = np.array(
        [
            [1.0, 0.0, 0.0, np.float64(np.inf)],
            [2.0, 1.0 / np.sqrt(2), 90.0, np.sqrt(2) * 2 * np.pi],
            [3.0, 1.0, 180.0, 1.0 * 2 * np.pi],
        ]
    )
    assert np.allclose(actual_do.all_arrays, expected_all_arrays)


def test_all_array_setter():
    actual_do = DiffractionObject()

    # Attempt to directly modify the property
    with pytest.raises(
        AttributeError,
        match="Direct modification of attribute 'all_arrays' is not allowed. "
        "Please use 'input_data' to modify 'all_arrays'.",
    ):
        actual_do.all_arrays = np.empty((4, 4))
```
