### ISSUE TITLE
factor out isfloat to a separate file

### ISSUE THREAD

**Issue by pavoljuhas** [diffpy/diffpy.utils#7]
Perhaps to diffpy.utils.typecheck module?

- [ ] check if there is any existing Python package with "isfloat" functionality.

**Comment by Sparks29032** [comment]
Could use isfloat from fastnumbers, compatible with 3.7+ (including 3.11).

Maybe good to create a new module `diffpy.utils.helpers` or something to put isfloat into. I would also like to put the exceptions in the `custom_exceptions.py` file into that new module.

**Comment by sbillinge** [comment]
I guess `isfloat` could go into `validators` if we make that (see my recent issue).  I think keeping `custom_exceptions` in a module with that name will make them more discoverable too, or mayb just `exceptions.py` .  So we have "validators", "exceptions", serializers" and so on .  It seems like a good organizational scheme for a repo that is called "utils".

btw, why does it have to be a float?  is an integer not ok?   Python automatically treats integers as floats if they are composed int a math expression with other floats.   What is the reason it has to be a float and not a number (more general)?

**Comment by Sparks29032** [comment]
The times isfloat is used is when checking whe a nonnumerical data type (like string) may encode a float. It can be given a more generic name like isnumber.

**Comment by bobleesj** [comment]
@lucas-lemos-da-silva has volunteered to resolve this issue. if you have any questions regarding this issue, please feel free to tag @sbillinge or @bobleesj here.

**Comment by bobleesj** [comment]
Lucas, please let us know today or tmr - if this issue is a bit challenging, I can resolve this issue since 3.6.0 is pending soon

**Comment by bobleesj** [comment]
It's most likely that we will wrap all of issues (except overview/release) under https://github.com/diffpy/diffpy.utils/milestone/2 by tomorrow (Monday night) per our target deadline.
