### ISSUE TITLE
re-cookiecutter diffpy.utils

### ISSUE THREAD

**Issue by sbillinge** [diffpy/diffpy.utils#94]
it was done very early in the process and the cookiecutter changed a lot by hte end.  For example, the readme is far from where we want it, but probably a few other things too.

After the latest round of cookiecutter smoothing on diffpy.srmise, we may want to recut diffpy.utils next.

**Comment by bobleesj** [comment]
I was about to make issues of older files such as rever.xsh, run_tests.py, etc. and the README format.

I can do it either now or after `diffpy.srmise`.

**Comment by sbillinge** [comment]
Let's get the cookiecutter where we want it, then recut everything.
